sudo: required
services:
  - docker

before_install:
  - docker build -t kolotushkina/docker-react-image -f Dockerfile.dev .

script:
  - docker run -e CI=true kolotushkina/docker-react-image npm run test 